# Generated by Django 6.0.5 on 2026-06-01 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(auto_now_add=True)),
                ('commits_last_30_days', models.IntegerField(default=0)),
                ('open_issues_count', models.IntegerField(default=0)),
                ('avg_issue_close_days', models.FloatField(default=0)),
                ('contributors_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Например: django/django', max_length=200, unique=True)),
                ('url', models.URLField(help_text='https://github.com/owner/repo')),
                ('description', models.TextField(blank=True)),
                ('stars', models.IntegerField(default=0)),
                ('forks', models.IntegerField(default=0)),
                ('last_commit_date', models.DateField(blank=True, null=True)),
                ('last_release_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReliabilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(default=0, help_text='Общая оценка 0-100')),
                ('commit_score', models.FloatField(default=0)),
                ('issues_score', models.FloatField(default=0)),
                ('release_score', models.FloatField(default=0)),
                ('community_score', models.FloatField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorer_app.activitysnapshot')),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reliability_score', to='scorer_app.repository')),
            ],
        ),
        migrations.AddField(
            model_name='activitysnapshot',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='scorer_app.repository'),
        ),
    ]
