# Generated by Django 6.0.5 on 2026-06-17 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reliabilityscore',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reliability_scores', to='scorer_app.repository'),
        ),
    ]
